### PR TITLE
Do not remove not existent tags

### PR DESCRIPTION
**Pull request by HolyPrapor**
Closes https://github.com/moira-alert/web2.0/issues/352

I assume that it's best to just remove the intersection. It shouldn't confuse users, because it reflects a real Moira state.

We could also color not existent triggers, but I don't think it's really necessary

### CODE REVIEW

**Comment by sashasushko** [comment]
@HolyPrapor thanks for PR. I'm not sure it is because of intersection. There are no possibles in our UI to choice unexist tags. I asked issue creator for details. 

I think that happens when user add tags to URL manually or open old URL with tags which was deleted.

I'm not sure what is correct solution. But, yes, maybe we should show to user some notification that tag was deleted. Let's ask more team members.

@beevee what do you think?

**Comment by HolyPrapor** [comment]
I am the issue creator, actually :)
It's just not me who posted an issue on Github.

You are correct, there are no possibilities to choose unexistent tags. But one can do that through query params. And if there is a tag in a query that does not exist it becomes very confusing, because you see a list of triggers with only existing tags instead of an empty list (see example in the original issue). 

My application may form an invalid link (with non-existent tags) to Moira upon user request. So I think that it's completely fine to show an empty list of triggers in that case. And, as I said, we can probably color unexistent tag names, just to indicate that the user query is probably incorrect.

What do you think?

**Comment by sashasushko** [comment]
It sounds great to me. But it's not enough to remove intersections function. We should change some UI also.

**Comment by sashasushko** [comment]
I'll try to find a way this week and I'll back.

**Comment by HolyPrapor** [comment]
Any improvements on this topic?

**Comment by sashasushko** [comment]
Nope. I have problems with local deploy Moira (web part) but I have no time to research the problem. So, pls, wait more 🙄

**Comment by HolyPrapor** [comment]
Hi, @sashasushko!

Any updates on this issue?

**Comment by sashasushko** [comment]
Hi, @HolyPrapor. Yes, the work in progress.

**Review by sol-un — APPROVED** [review]

**Pull request merged**
