### PR TITLE
[PERF] Defer pattern list rendering to improve speed

### PR DESCRIPTION
**Pull request by idoqo**
This is for the first Todo item in [#286](https://github.com/moira-alert/moira/issues/286) to make development easier and remove the error from the `/patterns` page. This is what the patterns page look like now:

Screenshot_2020-02-17 Moira - Patterns

### CODE REVIEW

**Comment by idoqo** [comment]
For the deferred rendering, the parent component is rendered first, and the items are added in steps. I tried using the [react-window](https://www.npmjs.com/package/react-window) package and while it is faster, it is harder to use with dynamic heights (we need the height to be dynamic when `showInfo` is `true` for a single pattern item). Below are the comparisons for 10,000 patterns:

Current master branch (no deferred rendering)

Screenshot_20200219_231157

With deferred rendering.

Screenshot_20200219_232843

With react-window package

Screenshot_20200219_231003

**Comment by sashasushko** [comment]
@idoqo thanks for pull request. I'll review it at weekend.

**Comment by sashasushko** [comment]
@idoqo i don't forgot. A lot of work :-(

**Comment by idoqo** [comment]
> @idoqo i don't forgot. A lot of work :-(

😅 Yeah, no problem.

**Comment by sashasushko** [comment]
@idoqo can you collaborate with @hv7214 about his PR - https://github.com/moira-alert/web2.0/pull/292

Did you affect each other?

**Comment by idoqo** [comment]
> @idoqo can you collaborate with @hv7214 about his PR - #292

Yes sure! Would work on it.

**Comment by hv7214** [comment]
@sashasushko we had a conversation regarding this, there is only one conflicting file PatternList.jsx so let my PR get merged and then @idoqo will solve conflicts accordingly.

**Comment by sashasushko** [comment]
@hv7214 pull request about sorting was merged. @idoqo your turn

**Comment by sashasushko** [comment]
@idoqo when you finish please tag me and remove WIP badge.

**Comment by idoqo** [comment]
> @idoqo when you finish please tag me and remove WIP badge.

Okay @sashasushko, it's ready for review now. I don't have the access to remove the WIP badge though.

**Comment by idoqo** [comment]
Hi @sashasushko, I tried resolving the conflicts between this and master and it affected way more files than I expected. I'm not sure how to resolve that, do you think a new PR would help?

**Pull request closed without merging**
