### PR TITLE
Add ability to type negative numbers in smpl mode (#168)

### PR DESCRIPTION
**Pull request by titusjaka**
bound with #168

### CODE REVIEW

**Comment by sashasushko** [comment]
This component also used in trigger edit form for TTL. Can TLL be negative number? If not, need validation for this case.

Also, if you modify component behaviour, add story to Storybook.

**Comment by titusjaka** [comment]
Yep, you are right. TTL should never be negative.

**Comment by titusjaka** [comment]
You are more competent 😉

**Comment by titusjaka** [comment]
Cool bro

**Pull request merged**
