### PR TITLE
Update storybook to 5.3.14

### PR DESCRIPTION
**Pull request by alishamohanty**
I checked, there were no breaking changes due to the migration. This PR solves #308. Let me know if there is anything I need to add.

### CODE REVIEW

**Comment by sashasushko** [comment]
@alishamohanty thanks. I'll review it ASAP

**Comment by beevee** [comment]
Closes moira-alert/moira#308

**Comment by sashasushko** [comment]
> I checked, there were no breaking changes due to the migration.

@alishamohanty do you check webpack config? I'm worried about this part of migration doc - https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecate-webpack-extend-mode

**Comment by alishamohanty** [comment]
Reading the docs thoroughly. Getting back to you after reading it.

**Comment by alishamohanty** [comment]
I checked the documentation, we are using in "extend-mode" configuration which is deprecated, so we need to shift it to "full-control" mode instead. And from storybook version 6, there will be only full-control mode customization (https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecate-webpack-extend-mode).

**Comment by alishamohanty** [comment]
I tried to change the "webpack.config.js" as described here https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecate-webpack-extend-mode but it gave lots of warning. The output of `yarn storybook --debug-webpack` gave this output (https://pastebin.com/PuP0SM73). Could you point me how to solve all the warnings?

**Comment by alishamohanty** [comment]
Hey @sashasushko could you look at the previous comments? I tried to search for different resources but unable to reproduce what is causing the warning. Could you please direct me what to do?

**Comment by sashasushko** [comment]
@alishamohanty yes, I saw it.

**Comment by sashasushko** [comment]
@alishamohanty now only option - wait till I can see :-(

**Comment by alishamohanty** [comment]
Sure @sashasushko.

**Comment by ani4aniket** [comment]
@sashasushko Is this resolved or should I try?

**Comment by sashasushko** [comment]
@ani4aniket now, issue paused, because we update some deps, which need custom Storybook webpack config. If it'll be success, we just drop webpack config. And this issue will close automatically

**Comment by sorovlad** [comment]
Updated into add regression testing https://github.com/moira-alert/web2.0/pull/311

**Pull request closed without merging**
