### PR TITLE
Add buttons to close #130

### LINKED ISSUE #130: Add buttons to delete all events and all notifications
We want to add 2 buttons on hidden url `/notifications`.

1. Remove all events:
`DELETE /api/event/all`

2. Remove all notifications
`DELETE /api/notification/all`

See https://github.com/moira-alert/moira/pull/73 for more details.

### PR DESCRIPTION
**Pull request by titusjaka**
This is how it looks:

firefox_2018-05-14_15-29-13

### CODE REVIEW

**Comment by titusjaka** [comment]
Changed a bit:

**Comment by titusjaka** [comment]
Changed a bit, so buttons align on single line on the right side.

### On small screen:
firefox_2018-05-15_13-53-12

### On wide screen:
firefox_2018-05-15_13-53-42

**Comment by sashasushko** [comment]
Ребейзнул на мастер

**Comment by borovskyav** [comment]
Вливать то будем?)

**Comment by sashasushko** [comment]
Порефачу и волью

**Pull request merged**
